# Generated by Django 2.2.9 on 2020-02-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200207_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ionMethod',
            field=models.CharField(choices=[('EI', 'EI-1'), ('CI', 'CI-2')], default='', max_length=20),
        ),
    ]
