# Generated by Django 2.2.9 on 2020-02-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200207_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='introMethod',
            field=models.CharField(choices=[('直接', '直接導入'), ('GC', 'GC導入(EI/CIのみ)'), ('LC', 'LC導入(ESI/APCIのみ)')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='ionKind',
            field=models.CharField(choices=[('+', '+イオン'), ('-', '-イオン')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='ionMethod',
            field=models.CharField(choices=[('EI', 'EI'), ('CI', 'CI'), ('FAV', 'FAV'), ('ESI', 'ESI'), ('APCI', 'APCI'), ('MALDI', 'MALDI')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='mass',
            field=models.CharField(choices=[('+', '+イオン'), ('-', '-イオン'), ('50 ～ 800', '50 ～ 800 ( EIのみ )'), ('800 ～ 1000', '800 ～ 1000'), ('1000 ～ 2000', '1000 ～ 2000'), ('2000 ～', '2000 ～')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='remarks',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='resolution',
            field=models.CharField(choices=[('LR', '低分解能[LR]測定（通常選択）'), ('HR', '高分解能[HR]測定（精密質量測定、MALDI選択不可）')], default='', max_length=20),
        ),
    ]
